---
- - :permit
  - MIT
  - :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:25:26.147815234 Z
- - :permit
  - Apache-2.0
  - :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:26:45.462466321 Z
- - :permit
  - ISC
  - :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:30:30.454867123 Z
- - :permit
  - CC0-1.0
  - :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:30:37.068637911 Z
- - :permit
  - Zlib
  - :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:32:42.268576261 Z
- - :permit
  - BSD-2-Clause
  - &1
    :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:35:02.086350845 Z
- - :permit
  - BSD-3-Clause
  - *1
- - :permit
  - 0BSD
  - *1
- - :permit
  - WTFPL
  - :who: 
    :why: 
    :versions: []
    :when: 2023-03-01 13:35:23.162368758 Z
